version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/src"
    update_schedule: "daily"
  - package_manager: "terraform"
    directory: "/infrastructure"
    update_schedule: "daily"
